import { useState } from 'react';
import { fmtUsd } from '../lib/format.js';

export default function Methodology({ meta, kpis }) {
  const [open, setOpen] = useState(false);
  return (
    <section className="panel p-4 sm:p-5">
      <button className="w-full flex items-center justify-between gap-3" onClick={() => setOpen((o) => !o)}>
        <div className="text-left">
          <div className="eyebrow mb-1">Read before citing</div>
          <h3 className="display text-[17px] font-semibold">Methodology & data caveats</h3>
        </div>
        <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="var(--text-dim)" strokeWidth="2" style={{ transform: open ? 'rotate(180deg)' : 'none', transition: 'transform .2s' }}><polyline points="6 9 12 15 18 9" /></svg>
      </button>
      {open && (
        <div className="mt-4 grid md:grid-cols-2 gap-x-8 gap-y-4 text-[13px] leading-relaxed fade-enter" style={{ color: 'var(--text-dim)' }}>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>What this is</h4>
            <p>A curated, hand-verified set of <strong style={{ color: 'var(--text)' }}>{meta.deal_count} food-tech VC rounds</strong> announced in the trailing twelve months ({meta.ttm_window.start} → {meta.ttm_window.end}), assembled from public sources. It is designed for <em>trend and structure</em> analysis, not as a complete market census.</p>
          </div>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>Sources</h4>
            <p>AgFunderNews weekly “AgriFood Signals” roundups (primary backbone), plus TechCrunch, Sifted, EU-Startups, Green Queen, Tech.eu, regional tech press (Inc42, Wamda, Disrupt Africa and peers), and company press releases. Records were then individually re-verified against primary sources in a second research pass — stages, lead investors, and amounts corrected where the roundup was wrong. Every record stores its source URLs and a confidence grade (high / medium / low).</p>
          </div>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>How money is counted</h4>
            <p>Headline capital ({fmtUsd(meta.headline_capital_usd)}) counts <strong style={{ color: 'var(--text)' }}>disclosed equity rounds only</strong> (Pre-seed → Growth). Debt and grants are kept in the dataset but excluded from capital totals by default. Non-USD rounds are converted at monthly-average ECB reference rates for the announcement month. <strong style={{ color: 'var(--text)' }}>Undisclosed amounts are never imputed</strong> — {meta.undisclosed_count} rounds carry no amount and drop out of every sum.</p>
          </div>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>Known bias</h4>
            <p>Public-source aggregation over-represents US/EU deals, English-language press, and larger or venture-hyped rounds (alt-protein, fermentation). It under-represents pre-seed/angel, non-English APAC/LATAM coverage, and quiet extensions. <strong style={{ color: 'var(--text)' }}>Absolute totals are floor estimates.</strong> Consumer food delivery and grocery quick-commerce are excluded by scope decision, since their mega-rounds would swamp food-innovation totals.</p>
          </div>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>Normalization</h4>
            <p>Stage labels are mapped to a canonical set via an editable taxonomy config; messy variants (“late-stage VC”, “SAFE”, “bridge”) map to their closest bucket. Companies are deduped by name + amount + date proximity. Segments are multi-label with one primary tag used for aggregation.</p>
          </div>
          <div>
            <h4 className="font-semibold mb-1.5" style={{ color: 'var(--text)' }}>Reproducible</h4>
            <p>The dataset is regenerated by a re-runnable pipeline (<span className="mono text-[11px]">npm run pipeline</span>) from a human-curated source file plus the taxonomy and FX configs. {meta.confidence_breakdown.low ?? 0} low-confidence and roundup-extracted records are flagged for individual verification (marked <span className="mono">*</span> in the table).</p>
          </div>
        </div>
      )}
    </section>
  );
}
